name: 'OpenAI PR Review'
description: 'A GitHub Action that reviews PRs using OpenAI API'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API key'
    required: true
  OPENAI_MODEL:
    description: 'OpenAI model deployment name'
    required: true
  OPENAI_ENDPOINT:
    description: 'OpenAI API endpoint'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
      shell: bash  # Specify the shell to use

    - name: Run the OpenAI PR Review script
      run: |
        source .venv/bin/activate
        python action.py
      shell: bash  # Specify the shell to use
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        OPENAI_MODEL: ${{ inputs.OPENAI_MODEL }}
        OPENAI_ENDPOINT: ${{ inputs.OPENAI_ENDPOINT }}
